# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02641f88cd6ee360bd5efc91c42abffccda99d833e545c220aa32b420bc2fa9894a0081c6602cd5e01eabff9d0180f32654c25c2bd690e0795a424a055a8916

test:
  secret_key_base: 5717570f85ab07256331f1291cf31b06b885faab8cdbce69ab9396a408597800b303d7276fff5df597a724758ed9dbd3f3936245a1cd413367482f7f26c614a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
